"""Data Transfer Objects (DTO) for analytical calculations and trend metrics."""

from __future__ import annotations

from typing import Dict, List, Literal, Optional
from pydantic import BaseModel, Field

TrendDirection = Literal["growing", "declining", "stable", "volatile"]
ConfidenceLevel = Literal["high", "medium", "low"]


class TimeSeriesPoint(BaseModel):
    """Normalized, continuous time-series data point."""

    date: str = Field(..., description="Normalized date string (YYYY-MM or YYYY-MM-DD).")
    timestamp: str = Field(..., description="Wikimedia timestamp (e.g. '2024010100').")
    views: int = Field(..., description="Raw pageviews in this period (0 if missing).")
    rolling_average: Optional[float] = Field(
        default=None,
        description="Smoothed rolling average (3-period for monthly, 7-period for daily).",
    )
    is_partial: bool = Field(
        default=False,
        description="True if the period is currently ongoing and metrics are partial.",
    )
    is_anomaly: bool = Field(
        default=False,
        description="True if this point is a statistical anomaly (Z-score > 2.5).",
    )
    z_score: Optional[float] = Field(
        default=None,
        description="Standardized Z-score of the views deviation from mean.",
    )


class TrendMetricsDTO(BaseModel):
    """Strictly typed quantitative business metrics calculated from time series."""

    total_views: int = Field(..., description="Sum of views across all periods in timeframe.")
    average_views: float = Field(..., description="Mean views per period.")
    median_views: float = Field(..., description="Median views per period.")
    std_dev: float = Field(..., description="Standard deviation of views.")
    volatility_score: float = Field(
        ...,
        description="Coefficient of variation (std_dev / mean), measuring trend noise.",
    )
    mom_growth_percent: Optional[float] = Field(
        default=None,
        description="Month-over-Month percentage change between the latest complete periods.",
    )
    yoy_growth_percent: Optional[float] = Field(
        default=None,
        description="Year-over-Year percentage change comparing latest period to same period previous year.",
    )
    peak_date: Optional[str] = Field(default=None, description="Date of highest view count.")
    peak_views: int = Field(default=0, description="Maximum views in a single period.")
    trough_date: Optional[str] = Field(default=None, description="Date of lowest view count.")
    trough_views: int = Field(default=0, description="Minimum views in a single period.")
    trend_direction: TrendDirection = Field(
        default="stable",
        description="Directional classification: 'growing', 'declining', 'stable', or 'volatile'.",
    )
    confidence_score: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Statistical confidence score (0.0 to 1.0) based on sample size and volatility.",
    )
    anomaly_count: int = Field(
        default=0,
        description="Number of anomalous spikes detected in the series.",
    )


class LanguageAnalyticsDTO(BaseModel):
    """Analytics for a specific Wikipedia language edition."""

    language: str
    article_title: Optional[str] = None
    found: bool = False
    metrics: Optional[TrendMetricsDTO] = None
    time_series: List[TimeSeriesPoint] = Field(default_factory=list)


class ComparisonMetricsDTO(BaseModel):
    """Comparative metrics across multiple Wikipedia language editions."""

    dominant_language: str = Field(..., description="Language edition with the highest view volume.")
    fastest_growing_language: Optional[str] = Field(
        default=None,
        description="Language edition with highest positive growth rate.",
    )
    language_shares_percent: Dict[str, float] = Field(
        default_factory=dict,
        description="Percentage breakdown of total topic attention by language.",
    )
    correlation_matrix: Dict[str, Dict[str, float]] = Field(
        default_factory=dict,
        description="Cross-language view volume correlation coefficients (-1.0 to 1.0).",
    )


class AIInterpretationDTO(BaseModel):
    """Executive qualitative synthesis generated by LLM from computed metrics."""

    trend_summary: str = Field(..., description="Executive summary of the trend.")
    direction: TrendDirection = Field(..., description="Overall trend direction.")
    confidence: ConfidenceLevel = Field(..., description="Confidence level in the findings.")
    seasonality_detected: bool = Field(
        default=False,
        description="Whether recurrent seasonal or weekend cycles are evident.",
    )
    key_drivers: List[str] = Field(
        default_factory=list,
        description="Bullet points explaining likely drivers, viral spikes, or shifts.",
    )
    business_takeaway: str = Field(
        ...,
        description="Actionable business or market takeaway from this data.",
    )


class AnalyticsResultDTO(BaseModel):
    """Complete unified output of the analytical engine."""

    topic: str
    source_topic: Optional[str] = None
    granularity: str = "monthly"
    start_date: str
    end_date: str
    languages: Dict[str, LanguageAnalyticsDTO] = Field(default_factory=dict)
    comparison: Optional[ComparisonMetricsDTO] = None
    ai_interpretation: Optional[AIInterpretationDTO] = None
